---
services:
  app-db:
    image: postgres:16
    environment:
      - PGUSER=bloodhound
      - POSTGRES_USER=bloodhound
      - POSTGRES_PASSWORD=bloodhoundcommunityedition
      - POSTGRES_DB=bloodhound
    # ports:
    #   - 127.0.0.1:5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bloodhound -d bloodhound -h 127.0.0.1 -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  graph-db:
    image: neo4j:4.4.42
    environment:
      - NEO4J_AUTH=neo4j/bloodhoundcommunityedition
      - NEO4J_dbms_allow__upgrade=true
    ports:
      - 127.0.0.1:7687:7687
      - 127.0.0.1:7474:7474
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null -q http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  bloodhound:
    image: specterops/bloodhound:latest
    environment:
      - bhe_disable_cypher_complexity_limit=false
      - bhe_enable_cypher_mutations=false
      - bhe_graph_query_memory_limit=2
      - bhe_database_connection=user=bloodhound password=bloodhoundcommunityedition dbname=bloodhound host=app-db
      - bhe_neo4j_connection=neo4j://neo4j:bloodhoundcommunityedition@graph-db:7687/
      - bhe_recreate_default_admin=false
      - bhe_graph_driver=neo4j
    ports:
      - 127.0.0.1:8080:8080
    ### Uncomment to use your own bloodhound.config.json to configure the application
    # volumes:
    #   - ./bloodhound.config.json:/bloodhound.config.json:ro
    depends_on:
      app-db:
        condition: service_healthy
      graph-db:
        condition: service_healthy
    restart: unless-stopped


